# Change these first
owner: mleczakm # Your GitHub organization or username, where this repository lives
repo: infrastructure-status # The name of this repository
delay: 2000

sites:
  - name: warsztatowniasensoryczna.pl
    url: https://warsztatowniasensoryczna.pl
  - name: skarbiec.mleczki.pl
    url: https://skarbiec.mleczki.pl
  - name: porin.pl
    url: https://porin.pl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.mleczki.pl
  baseUrl: $REPO
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status stron Mleczki
  introTitle: "**Infrastructure Status** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Monitoring dostępności stron, nad którymi sprawuję pieczę.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
