name = "uptime-dispatcher"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[env.production]
vars = { GH_OWNER = "mleczakm", GH_REPO = "infrastructure-status" }

[env.production.triggers]
crons = ["*/5 * * * *"]
