name: Update and Verify Cloudflare Domain
on:
  push:
    paths:
      - '.upptimerc.yml'
      - '.github/workflows/cloudflare-verify.yml'

jobs:
  cloudflare-dns:
    name: Update and Verify DNS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get config from .upptimerc.yml
        id: config
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: .upptimerc.yml

      - name: Verify and Update Cloudflare DNS
        if: steps.config.outputs['status-website.cname'] != ''
        uses: opszero/actions-cloudflare-dns@v3.1.0
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          type: CNAME
          name: ${{ steps.config.outputs['status-website.cname'] }}.
          content: ${{ steps.config.outputs['owner'] }}.github.io
          proxied: false
